[project]
name = "query-weather-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "gradio>=5.12.0",
    "llama-index>=0.12.11",
]
